### ISSUE TITLE
Trading System

### ISSUE THREAD

**Issue by Mythacri** [Mythacri/Mythacri-Foundry-Scripts#103]
Player characters should have the option to trade items with one another in an easy and visible way.

In general items that are traded are equipment and loot. So any item like class, feature, subclass, and race should be excluded. 

Trading in general is meant for players in this regard. So trading should be performed from the side bar. 

The trading window should be opened by clicking on a name on the sidebar and selecting "trade". This then opens a little window asking if the other player wants to trade. Accepting opens a window  for both players to deposit items to trade with. Similar to Havilon's trading system that we all loved.

**Comment by krbz999** [comment]
Replaced by #133 instead.
