### ISSUE TITLE
Pugilist Iron Chin

### ISSUE THREAD

**Issue by Mythacri** [Mythacri/Mythacri-Foundry-Scripts#110]
A new AC calculation needs to be added for the Pugilist Class. Pugilist AC is calculated as:

12 + Constitution Modifier (when not wearing armor or a shield of course)

**Comment by NMyers17** [comment]
Its worth nothing its an oddball because of the creators intention for the feature.
![Screenshot_20231129_182131_Reddit](https://github.com/Mythacri/Mythacri-Foundry-Scripts/assets/126525493/163298d9-88ad-4d2c-aca6-75455c75babb)

The wording on it, is fucking weird though i agree.

**Comment by krbz999** [comment]
This might need a secondary AC calculation, then. The current one in the PR fits unarmored; a second one for 'armored Iron Chin' might be needed.
