### ISSUE TITLE
Pugilist Moxie Feature

### ISSUE THREAD

**Issue by Mythacri** [Mythacri/Mythacri-Foundry-Scripts#112]
The Pugilist class has access to Moxie Features which need to be added as a feature type. 

The pugilist moxie features can be used by expending a designated number of Moxie Points for each Moxie Feature.

**Comment by krbz999** [comment]
We'll add the feature type, there doesn't seem to be anything else that needs doing. The document notes there being "more moxie features" but lists only the three initial ones and does not have any others.
