### ISSUE TITLE
Create utility method for populating loot list of enemy creatures with monster parts

### ISSUE THREAD

**Issue by krbz999** [Mythacri/Mythacri-Foundry-Scripts#123]
*Awaiting further detail from @Mythacri*

**Comment by Mythacri** [comment]
Further Detail Below:

Each creature type has a wide variety of parts that can come from them. To make it easier below is a list of what parts should not come from each creature type, as requested by @krbz999 :
### Aberration:
  "MYTHACRI.ResourceMonsterAntler": "Antler",
  "MYTHACRI.ResourceMonsterBreathSac": "Breath Sac",
  "MYTHACRI.ResourceMonsterEtherealIchor": "Ethereal Ichor",
  "MYTHACRI.ResourceMonsterFeathers": "Feathers",
  "MYTHACRI.ResourceMonsterInstructions": "Instructions",
  "MYTHACRI.ResourceMonsterMote": "Mote",
  "MYTHACRI.ResourceMonsterSap": "Sap",
  "MYTHACRI.ResourceMonsterTalon": "Talon",
  "MYTHACRI.ResourceMonsterTusk": "Tusk",

### Beast:
  "MYTHACRI.ResourceMonsterAcid": "Acid",
  "MYTHACRI.ResourceMonsterDust": "Dust",
  "MYTHACRI.ResourceMonsterEtherealIchor": "Ethereal Ichor",
  "MYTHACRI.ResourceMonsterInstructions": "Instructions",
  "MYTHACRI.ResourceMonsterMainEye": "Main Eye",
  "MYTHACRI.ResourceMonsterMote": "Mote",
  "MYTHACRI.ResourceMonsterMucus": "Mucus",
  "MYTHACRI.ResourceMonsterOil": "Oil",
  "MYTHACRI.ResourceMonsterPlating": "Plating",
  "MYTHACRI.ResourceMonsterScales": "Scales",
  "MYTHACRI.ResourceMonsterSkin": "Skin",
  "MYTHACRI.ResourceMonsterStinger": "Stinger",
  "MYTHACRI.ResourceMonsterTalon": "Talon",
  "MYTHACRI.ResourceMonsterTeeth": "Teeth",
  "MYTHACRI.ResourceMonsterTentacle": "Tentacle",
  "MYTHACRI.ResourceMonsterTusk": "Tusk",

### Celestial:
  "MYTHACRI.ResourceMonsterAcid": "Acid",
  "MYTHACRI.ResourceMonsterAntenna": "Antenna",
  "MYTHACRI.ResourceMonsterAntler": "Antler",
  "MYTHACRI.ResourceMonsterBlood": "Blood",
  "MYTHACRI.ResourceMonsterBreathSac": "Breath Sac",
  "MYTHACRI.ResourceMonsterCarapace": "Carapace",
  "MYTHACRI.ResourceMonsterEgg": "Egg",
  "MYTHACRI.ResourceMonsterEtherealIchor": "Ethereal Ichor",
  "MYTHACRI.ResourceMonsterHide": "Hide",
  "MYTHACRI.ResourceMonsterInstructions": "Instructions",
  "MYTHACRI.ResourceMonsterMainEye": "Main Eye",
  "MYTHACRI.ResourceMonsterMote": "Mote",
  "MYTHACRI.ResourceMonsterMucus": "Mucus",
  "MYTHACRI.ResourceMonsterOil": "Oil",
  "MYTHACRI.ResourceMonsterPincer": "Pincer",
  "MYTHACRI.ResourceMonsterPlating": "Plating",
  "MYTHACRI.ResourceMonsterPoisonGland": "Poison Gland",
  "MYTHACRI.ResourceMonsterSap": "Sap",
  "MYTHACRI.ResourceMonsterStinger": "Stinger",
  "MYTHACRI.ResourceMonsterTalon": "Talon",
  "MYTHACRI.ResourceMonsterTentacle": "Tentacle",
  "MYTHACRI.ResourceMonsterTusk": "Tusk",

### Construct:
  "MYTHACRI.ResourceMonsterAcid": "Acid",
  "MYTHACRI.ResourceMonsterAntenna": "Antenna",
  "MYTHACRI.ResourceMonsterAntler": "Antler",
  "MYTHACRI.ResourceMonsterBreathSac": "Breath Sac",
  "MYTHACRI.ResourceMonsterCarapace": "Carapace",
  "MYTHACRI.ResourceMonsterClaws": "Claws",
  "MYTHACRI.ResourceMonsterDust": "Dust",
  "MYTHACRI.ResourceMonsterEgg": "Egg",
  "MYTHACRI.ResourceMonsterEtherealIchor": "Ethereal Ichor",
  "MYTHACRI.ResourceMonsterEye": "Eye",
  "MYTHACRI.ResourceMonsterFat": "Fat",
  "MYTHACRI.ResourceMonsterFeathers": "Feathers",
  "MYTHACRI.ResourceMonsterFin": "Fin",
  "MYTHACRI.ResourceMonsterHeart": "Heart",
  "MYTHACRI.ResourceMonsterHide": "Hide",
  "MYTHACRI.ResourceMonsterHorn": "Horn",
  "MYTHACRI.ResourceMonsterLiver": "Liver",
  "MYTHACRI.ResourceMonsterMainEye": "Main Eye",
  "MYTHACRI.ResourceMonsterMote": "Mote",
  "MYTHACRI.ResourceMonsterPincer": "Pincer",
  "MYTHACRI.ResourceMonsterPoisonGland": "Poison Gland",
  "MYTHACRI.ResourceMonsterSap": "Sap",
  "MYTHACRI.ResourceMonsterScales": "Scales",
  "MYTHACRI.ResourceMonsterSkin": "Skin",
  "MYTHACRI.ResourceMonsterStinger": "Stinger",
  "MYTHACRI.ResourceMonsterTalon": "Talon",
  "MYTHACRI.ResourceMonsterTeeth": "Teeth",
  "MYTHACRI.ResourceMonsterTentacle": "Tentacle",
  "MYTHACRI.ResourceMonsterTusk": "Tusk",

### Dragon:
  "MYTHACRI.ResourceMonsterAcid": "Acid",
  "MYTHACRI.ResourceMonsterAntenna": "Antenna",
  "MYTHACRI.ResourceMonsterAntler": "Antler",
  "MYTHACRI.ResourceMonsterBlood": "Blood",
  "MYTHACRI.ResourceMonsterBrain": "Brain",
  "MYTHACRI.ResourceMonsterCarapace": "Carapace",
  "MYTHACRI.ResourceMonsterDust": "Dust",
  "MYTHACRI.ResourceMonsterEtherealIchor": "Ethereal Ichor",
  "MYTHACRI.ResourceMonsterFin": "Fin",
  "MYTHACRI.ResourceMonsterHide": "Hide",
  "MYTHACRI.ResourceMonsterInstructions": "Instructions",
  "MYTHACRI.ResourceMonsterMainEye": "Main Eye",
  "MYTHACRI.ResourceMonsterMote": "Mote",
  "MYTHACRI.ResourceMonsterMucus": "Mucus",
  "MYTHACRI.ResourceMonsterOil": "Oil",
  "MYTHACRI.ResourceMonsterPincer": "Pincer",
  "MYTHACRI.ResourceMonsterPlating": "Plating",
  "MYTHACRI.ResourceMonsterPoisonGland": "Poison Gland",
  "MYTHACRI.ResourceMonsterSap": "Sap",
  "MYTHACRI.ResourceMonsterSkin": "Skin",
  "MYTHACRI.ResourceMonsterStinger": "Stinger",
  "MYTHACRI.ResourceMonsterTalon": "Talon",
  "MYTHACRI.ResourceMonsterTentacle": "Tentacle",
  "MYTHACRI.ResourceMonsterTusk": "Tusk",

### Elemental:
  "MYTHACRI.ResourceMonsterAcid": "Acid",
  "MYTHACRI.ResourceMonsterAntenna": "Antenna",
  "MYTHACRI.ResourceMonsterAntler": "Antler",
  "MYTHACRI.ResourceMonsterBlood": "Blood",
  "MYTHACRI.ResourceMonsterBrain": "Brain",
  "MYTHACRI.ResourceMonsterBreathSac": "Breath Sac",
  "MYTHACRI.ResourceMonsterClaws": "Claws",
  "MYTHACRI.ResourceMonsterEgg": "Egg",
  "MYTHACRI.ResourceMonsterEtherealIchor": "Ethereal Ichor",
  "MYTHACRI.ResourceMonsterFat": "Fat",
  "MYTHACRI.ResourceMonsterFeathers": "Feathers",
  "MYTHACRI.ResourceMonsterFin": "Fin",
  "MYTHACRI.ResourceMonsterFlesh": "Flesh",
  "MYTHACRI.ResourceMonsterHeart": "Heart",
  "MYTHACRI.ResourceMonsterHide": "Hide",
  "MYTHACRI.ResourceMonsterInstructions": "Instructions",
  "MYTHACRI.ResourceMonsterLiver": "Liver",
  "MYTHACRI.ResourceMonsterMainEye": "Main Eye",
  "MYTHACRI.ResourceMonsterMucus": "Mucus",
  "MYTHACRI.ResourceMonsterOil": "Oil",
  "MYTHACRI.ResourceMonsterPincer": "Pincer",
  "MYTHACRI.ResourceMonsterPlating": "Plating",
  "MYTHACRI.ResourceMonsterPoisonGland": "Poison Gland",
  "MYTHACRI.ResourceMonsterSap": "Sap",
  "MYTHACRI.ResourceMonsterScales": "Scales",
  "MYTHACRI.ResourceMonsterSkin": "Skin",
  "MYTHACRI.ResourceMonsterStinger": "Stinger",
  "MYTHACRI.ResourceMonsterTalon": "Talon",
  "MYTHACRI.ResourceMonsterTeeth": "Teeth",
  "MYTHACRI.ResourceMonsterTentacle": "Tentacle",
  "MYTHACRI.ResourceMonsterTusk": "Tusk",

### Fey:
  "MYTHACRI.ResourceMonsterAcid": "Acid",
  "MYTHACRI.ResourceMonsterBrain": "Brain",
  "MYTHACRI.ResourceMonsterBreathSac": "Breath Sac",
  "MYTHACRI.ResourceMonsterCarapace": "Carapace",
  "MYTHACRI.ResourceMonsterDust": "Dust",
  "MYTHACRI.ResourceMonsterEgg": "Egg",
  "MYTHACRI.ResourceMonsterEtherealIchor": "Ethereal Ichor",
  "MYTHACRI.ResourceMonsterFin": "Fin",
  "MYTHACRI.ResourceMonsterHide": "Hide",
  "MYTHACRI.ResourceMonsterInstructions": "Instructions",
  "MYTHACRI.ResourceMonsterMainEye": "Main Eye",
  "MYTHACRI.ResourceMonsterMote": "Mote",
  "MYTHACRI.ResourceMonsterMucus": "Mucus",
  "MYTHACRI.ResourceMonsterOil": "Oil",
  "MYTHACRI.ResourceMonsterPincer": "Pincer",
  "MYTHACRI.ResourceMonsterPlating": "Plating",
  "MYTHACRI.ResourceMonsterPoisonGland": "Poison Gland",
  "MYTHACRI.ResourceMonsterSap": "Sap",
  "MYTHACRI.ResourceMonsterScales": "Scales",
  "MYTHACRI.ResourceMonsterStinger": "Stinger",
  "MYTHACRI.ResourceMonsterTalon": "Talon",
  "MYTHACRI.ResourceMonsterTentacle": "Tentacle",
  "MYTHACRI.ResourceMonsterTusk": "Tusk",

### Fiend:
  "MYTHACRI.ResourceMonsterAcid": "Acid",
  "MYTHACRI.ResourceMonsterAntenna": "Antenna",
  "MYTHACRI.ResourceMonsterAntler": "Antler",
  "MYTHACRI.ResourceMonsterBreathSac": "Breath Sac",
  "MYTHACRI.ResourceMonsterCarapace": "Carapace",
  "MYTHACRI.ResourceMonsterEgg": "Egg",
  "MYTHACRI.ResourceMonsterEtherealIchor": "Ethereal Ichor",
  "MYTHACRI.ResourceMonsterFin": "Fin",
  "MYTHACRI.ResourceMonsterHide": "Hide",
  "MYTHACRI.ResourceMonsterInstructions": "Instructions",
  "MYTHACRI.ResourceMonsterMainEye": "Main Eye",
  "MYTHACRI.ResourceMonsterMote": "Mote",
  "MYTHACRI.ResourceMonsterMucus": "Mucus",
  "MYTHACRI.ResourceMonsterOil": "Oil",
  "MYTHACRI.ResourceMonsterPlating": "Plating",
  "MYTHACRI.ResourceMonsterSap": "Sap",
  "MYTHACRI.ResourceMonsterTentacle": "Tentacle",
  "MYTHACRI.ResourceMonsterTusk": "Tusk",

### Giant:
  "MYTHACRI.ResourceMonsterAcid": "Acid",
  "MYTHACRI.ResourceMonsterAntenna": "Antenna",
  "MYTHACRI.ResourceMonsterAntler": "Antler",
  "MYTHACRI.ResourceMonsterBreathSac": "Breath Sac",
  "MYTHACRI.ResourceMonsterCarapace": "Carapace",
  "MYTHACRI.ResourceMonsterClaws": "Claws",
  "MYTHACRI.ResourceMonsterDust": "Dust",
  "MYTHACRI.ResourceMonsterEgg": "Egg",
  "MYTHACRI.ResourceMonsterEtherealIchor": "Ethereal Ichor",
  "MYTHACRI.ResourceMonsterFeathers": "Feathers",
  "MYTHACRI.ResourceMonsterFin": "Fin",
  "MYTHACRI.ResourceMonsterHide": "Hide",
  "MYTHACRI.ResourceMonsterHorn": "Horn",
  "MYTHACRI.ResourceMonsterInstructions": "Instructions",
  "MYTHACRI.ResourceMonsterMainEye": "Main Eye",
  "MYTHACRI.ResourceMonsterMote": "Mote",
  "MYTHACRI.ResourceMonsterMucus": "Mucus",
  "MYTHACRI.ResourceMonsterOil": "Oil",
  "MYTHACRI.ResourceMonsterPincer": "Pincer",
  "MYTHACRI.ResourceMonsterPlating": "Plating",
  "MYTHACRI.ResourceMonsterPoisonGland": "Poison Gland",
  "MYTHACRI.ResourceMonsterSap": "Sap",
  "MYTHACRI.ResourceMonsterScales": "Scales",
  "MYTHACRI.ResourceMonsterStinger": "Stinger",
  "MYTHACRI.ResourceMonsterTalon": "Talon",
  "MYTHACRI.ResourceMonsterTentacle": "Tentacle",
  "MYTHACRI.ResourceMonsterTusk": "Tusk",

### Humanoid:
  "MYTHACRI.ResourceMonsterAcid": "Acid",
  "MYTHACRI.ResourceMonsterAntenna": "Antenna",
  "MYTHACRI.ResourceMonsterAntler": "Antler",
  "MYTHACRI.ResourceMonsterBone": "Bone",
  "MYTHACRI.ResourceMonsterBrain": "Brain",
  "MYTHACRI.ResourceMonsterBreathSac": "Breath Sac",
  "MYTHACRI.ResourceMonsterCarapace": "Carapace",
  "MYTHACRI.ResourceMonsterClaws": "Claws",
  "MYTHACRI.ResourceMonsterDust": "Dust",
  "MYTHACRI.ResourceMonsterEgg": "Egg",
  "MYTHACRI.ResourceMonsterEtherealIchor": "Ethereal Ichor",
  "MYTHACRI.ResourceMonsterEye": "Eye",
  "MYTHACRI.ResourceMonsterFat": "Fat",
  "MYTHACRI.ResourceMonsterFeathers": "Feathers",
  "MYTHACRI.ResourceMonsterFin": "Fin",
  "MYTHACRI.ResourceMonsterFlesh": "Flesh",
  "MYTHACRI.ResourceMonsterHeart": "Heart",
  "MYTHACRI.ResourceMonsterHide": "Hide",
  "MYTHACRI.ResourceMonsterHorn": "Horn",
  "MYTHACRI.ResourceMonsterInstructions": "Instructions",
  "MYTHACRI.ResourceMonsterLiver": "Liver",
  "MYTHACRI.ResourceMonsterMainEye": "Main Eye",
  "MYTHACRI.ResourceMonsterMote": "Mote",
  "MYTHACRI.ResourceMonsterMucus": "Mucus",
  "MYTHACRI.ResourceMonsterOil": "Oil",
  "MYTHACRI.ResourceMonsterPincer": "Pincer",
  "MYTHACRI.ResourceMonsterPlating": "Plating",
  "MYTHACRI.ResourceMonsterPoisonGland": "Poison Gland",
  "MYTHACRI.ResourceMonsterSap": "Sap",
  "MYTHACRI.ResourceMonsterScales": "Scales",
  "MYTHACRI.ResourceMonsterSkin": "Skin",
  "MYTHACRI.ResourceMonsterStinger": "Stinger",
  "MYTHACRI.ResourceMonsterTalon": "Talon",
  "MYTHACRI.ResourceMonsterTeeth": "Teeth",
  "MYTHACRI.ResourceMonsterTentacle": "Tentacle",
  "MYTHACRI.ResourceMonsterTusk": "Tusk",

### Monstrosity:
  "MYTHACRI.ResourceMonsterBrain": "Brain",
  "MYTHACRI.ResourceMonsterBreathSac": "Breath Sac",
  "MYTHACRI.ResourceMonsterDust": "Dust",
  "MYTHACRI.ResourceMonsterEtherealIchor": "Ethereal Ichor",
  "MYTHACRI.ResourceMonsterInstructions": "Instructions",
  "MYTHACRI.ResourceMonsterMainEye": "Main Eye",
  "MYTHACRI.ResourceMonsterMote": "Mote",
  "MYTHACRI.ResourceMonsterMucus": "Mucus",
  "MYTHACRI.ResourceMonsterOil": "Oil",
  "MYTHACRI.ResourceMonsterPlating": "Plating",
  "MYTHACRI.ResourceMonsterSap": "Sap",

### Ooze:
  "MYTHACRI.ResourceMonsterAntenna": "Antenna",
  "MYTHACRI.ResourceMonsterAntler": "Antler",
  "MYTHACRI.ResourceMonsterBlood": "Blood",
  "MYTHACRI.ResourceMonsterBone": "Bone",
  "MYTHACRI.ResourceMonsterBrain": "Brain",
  "MYTHACRI.ResourceMonsterBreathSac": "Breath Sac",
  "MYTHACRI.ResourceMonsterCarapace": "Carapace",
  "MYTHACRI.ResourceMonsterClaws": "Claws",
  "MYTHACRI.ResourceMonsterDust": "Dust",
  "MYTHACRI.ResourceMonsterEgg": "Egg",
  "MYTHACRI.ResourceMonsterEtherealIchor": "Ethereal Ichor",
  "MYTHACRI.ResourceMonsterEye": "Eye",
  "MYTHACRI.ResourceMonsterFat": "Fat",
  "MYTHACRI.ResourceMonsterFeathers": "Feathers",
  "MYTHACRI.ResourceMonsterFin": "Fin",
  "MYTHACRI.ResourceMonsterFlesh": "Flesh",
  "MYTHACRI.ResourceMonsterHeart": "Heart",
  "MYTHACRI.ResourceMonsterHide": "Hide",
  "MYTHACRI.ResourceMonsterHorn": "Horn",
  "MYTHACRI.ResourceMonsterInstructions": "Instructions",
  "MYTHACRI.ResourceMonsterLiver": "Liver",
  "MYTHACRI.ResourceMonsterMainEye": "Main Eye",
  "MYTHACRI.ResourceMonsterMote": "Mote",
  "MYTHACRI.ResourceMonsterOil": "Oil",
  "MYTHACRI.ResourceMonsterPincer": "Pincer",
  "MYTHACRI.ResourceMonsterPlating": "Plating",
  "MYTHACRI.ResourceMonsterPoisonGland": "Poison Gland",
  "MYTHACRI.ResourceMonsterSap": "Sap",
  "MYTHACRI.ResourceMonsterScales": "Scales",
  "MYTHACRI.ResourceMonsterSkin": "Skin",
  "MYTHACRI.ResourceMonsterStinger": "Stinger",
  "MYTHACRI.ResourceMonsterTalon": "Talon",
  "MYTHACRI.ResourceMonsterTeeth": "Teeth",
  "MYTHACRI.ResourceMonsterTentacle": "Tentacle",
  "MYTHACRI.ResourceMonsterTusk": "Tusk",

### Plant:
  "MYTHACRI.ResourceMonsterAcid": "Acid",
  "MYTHACRI.ResourceMonsterAntenna": "Antenna",
  "MYTHACRI.ResourceMonsterAntler": "Antler",
  "MYTHACRI.ResourceMonsterBlood": "Blood",
  "MYTHACRI.ResourceMonsterBone": "Bone",
  "MYTHACRI.ResourceMonsterBrain": "Brain",
  "MYTHACRI.ResourceMonsterBreathSac": "Breath Sac",
  "MYTHACRI.ResourceMonsterCarapace": "Carapace",
  "MYTHACRI.ResourceMonsterClaws": "Claws",
  "MYTHACRI.ResourceMonsterDust": "Dust",
  "MYTHACRI.ResourceMonsterEgg": "Egg",
  "MYTHACRI.ResourceMonsterEtherealIchor": "Ethereal Ichor",
  "MYTHACRI.ResourceMonsterEye": "Eye",
  "MYTHACRI.ResourceMonsterFat": "Fat",
  "MYTHACRI.ResourceMonsterFeathers": "Feathers",
  "MYTHACRI.ResourceMonsterFin": "Fin",
  "MYTHACRI.ResourceMonsterFlesh": "Flesh",
  "MYTHACRI.ResourceMonsterHeart": "Heart",
  "MYTHACRI.ResourceMonsterHide": "Hide",
  "MYTHACRI.ResourceMonsterHorn": "Horn",
  "MYTHACRI.ResourceMonsterInstructions": "Instructions",
  "MYTHACRI.ResourceMonsterLiver": "Liver",
  "MYTHACRI.ResourceMonsterMainEye": "Main Eye",
  "MYTHACRI.ResourceMonsterMote": "Mote",
  "MYTHACRI.ResourceMonsterMucus": "Mucus",
  "MYTHACRI.ResourceMonsterOil": "Oil",
  "MYTHACRI.ResourceMonsterPincer": "Pincer",
  "MYTHACRI.ResourceMonsterPlating": "Plating",
  "MYTHACRI.ResourceMonsterPoisonGland": "Poison Gland",
  "MYTHACRI.ResourceMonsterScales": "Scales",
  "MYTHACRI.ResourceMonsterTalon": "Talon",
  "MYTHACRI.ResourceMonsterTeeth": "Teeth",
  "MYTHACRI.ResourceMonsterTentacle": "Tentacle",
  "MYTHACRI.ResourceMonsterTusk": "Tusk",

### Undead:
  "MYTHACRI.ResourceMonsterAcid": "Acid",
  "MYTHACRI.ResourceMonsterAntenna": "Antenna",
  "MYTHACRI.ResourceMonsterAntler": "Antler",
  "MYTHACRI.ResourceMonsterBreathSac": "Breath Sac",
  "MYTHACRI.ResourceMonsterCarapace": "Carapace",
  "MYTHACRI.ResourceMonsterClaws": "Claws",
  "MYTHACRI.ResourceMonsterDust": "Dust",
  "MYTHACRI.ResourceMonsterEgg": "Egg",
  "MYTHACRI.ResourceMonsterFat": "Fat",
  "MYTHACRI.ResourceMonsterFeathers": "Feathers",
  "MYTHACRI.ResourceMonsterFin": "Fin",
  "MYTHACRI.ResourceMonsterHeart": "Heart",
  "MYTHACRI.ResourceMonsterHide": "Hide",
  "MYTHACRI.ResourceMonsterHorn": "Horn",
  "MYTHACRI.ResourceMonsterInstructions": "Instructions",
  "MYTHACRI.ResourceMonsterLiver": "Liver",
  "MYTHACRI.ResourceMonsterMainEye": "Main Eye",
  "MYTHACRI.ResourceMonsterMote": "Mote",
  "MYTHACRI.ResourceMonsterMucus": "Mucus",
  "MYTHACRI.ResourceMonsterOil": "Oil",
  "MYTHACRI.ResourceMonsterPincer": "Pincer",
  "MYTHACRI.ResourceMonsterPlating": "Plating",
  "MYTHACRI.ResourceMonsterPoisonGland": "Poison Gland",
  "MYTHACRI.ResourceMonsterSap": "Sap",
  "MYTHACRI.ResourceMonsterScales": "Scales",
  "MYTHACRI.ResourceMonsterSkin": "Skin",
  "MYTHACRI.ResourceMonsterStinger": "Stinger",
  "MYTHACRI.ResourceMonsterTalon": "Talon",
  "MYTHACRI.ResourceMonsterTentacle": "Tentacle",
  "MYTHACRI.ResourceMonsterTusk": "Tusk",
