### ISSUE TITLE
Ship Sheet

### ISSUE THREAD

**Issue by Mythacri** [Mythacri/Mythacri-Foundry-Scripts#132]
The vehicle sheet needs some modifications in order to better work for the rules that we are adapting from Delver's Guide to Beast World.

- [ ] Remove Crew and passengers. There should only be one section of cargo for the ship.
- [ ] Cargo Capacity should be measured int quantity of crates instead of tons of weight
- [ ] Add a Tab for actors on the ship
- [ ] - [ ] Add helmsman, shipwright, and spell driver sections that designates one actor as helmsman to reference their abilities to certain actions or features like AC. Dex or Wis and water vehicle proficiency for helmsman, Dex or Int and carpenters proficiency for shipwright, spell modifier + proficiency for spelldriver
- [ ] Remove or Hide threshhold and mishap values under HP
- [ ] Remove stationary armor class for ship
- [ ] The features Tab contents needs to be replaced with four categories: Features, Vehicle Components, Vehicle Fittings, and Spelldriving Modes.
          - [ ] Vehicle Components = Siege Weapons (Subtype of Weapons)
          - [ ] Vehicle Fittings = All Equipment
          - [ ] Spelldriving Modes = New Feature Subtype
          - [ ] Features = All Other Features

**Comment by krbz999** [comment]
> Vehicle Fittings = All Equipment

So if I drop some set of plate armor onto the sheet...?

**Comment by Mythacri** [comment]
> > Vehicle Fittings = All Equipment
> 
> 
> 
> So if I drop some set of plate armor onto the sheet...?

That is an excellent point....in that case we should restrict it to the "Vehicle Equipment" subtype and allow regular equipment to be put in Cargo? Any excess weapons or equipment or miscellaneous items can be out in a separate section on the cargo page or features page if the cargo pages quantity based storage does not allow for it.

**Comment by Mythacri** [comment]
Okay. Underneath the Cargo Tab there are two headers to organize items.

Supplies:
- Inventory Actors
- Ship Supplies (A new type of consumable item, that will need to be added)

Misc*:
- All types of items that do not have a designated place on the vehicle sheet. Regular weapons, loot, resources, etc.

*(Narratively 'Misc' isn't an actual inventory. It's just meant to prevent issues with losing items when transferring them. I assume certain players will be keen to fully organize the items during downtime or between sessions)
