### ISSUE TITLE
Add new shield types and optionally the 'Light' property to equipment

### ISSUE THREAD

**Issue by Mythacri** [Mythacri/Mythacri-Foundry-Scripts#156]
Add in new shield types for player proficiencies:

- [ ] Buckler Shield: +1 AC, Light Melee Weapon 1d4 Bludgeoning
- [ ] Tower Shield: +3 AC, 16 STR Requirement

**Comment by krbz999** [comment]
On buckler: Either this is a light melee weapon, or it is a shield that can do a melee attack. There is a difference, and we can do only one of these things. Assuming the latter, we should also see about adding 'light' as a valid property for Equipment.

**Comment by Mythacri** [comment]
This would be a shield that can do a melee attack yes. As far as the light property goes that seems like a good idea but is it necessary?

**Comment by krbz999** [comment]
It would be correct, and it would be trivial.

**Comment by krbz999** [comment]
This never came up again. Do we still want this? The issue is nearly a year old.

**Comment by Mythacri** [comment]
Good point. I believe we can now just add an attack to the buckler shield so I will probably just do that. No need to overcomplicate things. I will take a look at this later today.
