### ISSUE TITLE
Display the tooltip when hovering above the selected recipe image in the crafting window

### ISSUE THREAD

**Issue by InnilToo** [Mythacri/Mythacri-Foundry-Scripts#192]
As the title says, in the crafting window, when the user hovers above the selected recipe image on the right side of the window, it would be handy if it displayed the item's tooltip. It currently displays the tooltip if hovering above the image on the left side of the crafting window (recipe select).
![image](https://github.com/user-attachments/assets/c25e7381-ae6b-4d4e-81ac-cac22e220bd9)

**Comment by krbz999** [comment]
Toss it on the pile!
