### ISSUE TITLE
Alchemy Crafting: Subsubtypes

### ISSUE THREAD

**Issue by krbz999** [Mythacri/Mythacri-Foundry-Scripts#200]
Building on #183, which added alchemical subtypes (flower, herb, mushroom, crystal), we need identifiers for what the subsubtypes are.

Crystal: 

Flower:

Herb:

Mushroom:

**Comment by Mythacri** [comment]
Thank you sir!

Alchemy Crafting subtypes are as follows:

Crystals:
- [ ] Pyroclast
- [ ] Aetherite
- [ ] Stormshard
- [ ] Solunat

Flowers:
- [ ] Moonflower
- [ ] Gablips
- [ ] Manastaracae
- [ ] Brassic Splash

Herbs:
- [ ] Heartsease
- [ ] Vitamoss
- [ ] Ambergrain
- [ ] Ebonbark

Mushrooms
- [ ] Ascoverte
- [ ] Ruby Veil
- [ ] Whispering Spore
- [ ] Spectre Springs
