### ISSUE TITLE
Crafting System

### ISSUE THREAD

**Issue by Mythacri** [Mythacri/Mythacri-Foundry-Scripts#40]
A crafting interface is needed to accommodate the homebrew systems in the Pirate Campaign including Runecarving, Monster Crafting, and Monster Cooking. The best option for this would be to base it on Materia Medica, where a player is presented with a window detailing different craftable items and is able to craft them using a button. The interface for the pirate campaign will be different. The following will be needed for each system.

- [ ] A recipe item that can reference both an equipment item that can be crafted and loot items that are used for crafting. These items should be referenced using their identifiers.

- [ ]  GM Interface which lists all recipes created in the world. One interface for each system would be most effective. This interface should list the recipes from top to bottom and the characters from left to right. For each character, there should be a box to check to indicate whether the character knows the recipe for crafting such an item or not.

- [ ] Player interface available on the character sheet. By clicking on 'Runecarving' a separate window should open up that lists the player's known recipes. If possible, recipes that are able to be crafted should be placed at the top of the list in alphabetical order. By clicking on a recipe a confirmation box should appear asking if the player wants to craft the item from the recipe and the loot items being used for the recipe should be listed as well, noting that they will be consumed.

**Comment by krbz999** [comment]
One 'base' js `class` that the specialized crafting interfaces use would make the code more manageable. This base class would hold methods to derive a lists of items and recipes, and the subclasses would do their own filtering. They can _perhaps_ also use the same hbs template but with different titles.
