### ISSUE TITLE
'Recipe' item and sheet

### ISSUE THREAD

**Issue by krbz999** [Mythacri/Mythacri-Foundry-Scripts#44]
Related to #40.

Create a new item type, `recipe`, and an associated sheet. This would store data for what item it creates (storing a uuid), as well as what items are required to make it (using identifiers).

Some ideas for properties for the schema:
- The created item (string, stores a uuid), a direct reference to the item that will be created (likely an item stored in a different compendium).
- Ingredients (strings, an array of identifiers), to link to what items are needed to make the item.
- Type (string, either rune, cooking, monster, or spirit), to denote what crafting type this recipe belongs to.
- Basic (boolean), whether this is a 'basic' recipe that is learned immediately when a character opts into this type of crafting.

**Comment by Mythacri** [comment]
This all looks correct, thank you for putting it into proper words
