### ISSUE TITLE
Suggestion: Add an 'Identifiers' settings menu

### ISSUE THREAD

**Issue by krbz999** [Mythacri/Mythacri-Foundry-Scripts#51]
It would be good to have one central location where various ids or identifiers are stored and can be adjusted by the GM.

Some ideas:
- The key of the pack (or packs?) that contain recipe items.
- The id of the folder that contains the party members' actors (comes in handy often).
- The data folder(s) for sound files (for #35).
- The key of the pack with resource items.

**Comment by Mythacri** [comment]
I would suggest also adding the key of the pack(s) that contain the loot items. They will be generic and set in place to begin with but could possibly have something specific or new added later.
