### ISSUE TITLE
Pip Bar

### ISSUE THREAD

**Issue by Mythacri** [Mythacri/Mythacri-Foundry-Scripts#68]
The experience bar needs to be split into 10 unique sections that can be filled in as players progress. This way players have more of a sense of how well they are leveling up.

**Comment by krbz999** [comment]
The easiest approach is to still, technically, use XP but present it differently.
- [ ] Change the xp thresholds and required amounts in the system config.
- [ ] Adjust the look of the xp bar on actor sheets.
- [ ] Adjust the labels present on the actor sheets.
- [ ] Implement an api method to grant (or set) all player-owned `character`-type actors' current xp level?
