### ISSUE TITLE
Display jumping distance on character sheet

### ISSUE THREAD

**Issue by InnilToo** [Mythacri/Mythacri-Foundry-Scripts#79]
Because no one can ever remember how jumping works, having the value displayed on the sheet itself (for example hover in movement) would speed things up.

https://fexlabs.com/5ejump/

**Comment by krbz999** [comment]
A dynamically rendered tooltip when hovering over the Movement on the character sheet would be a decent addition.

**Comment by InnilToo** [comment]
No idea where to even fit this on the new character sheets.
