### ISSUE TITLE
Spirit Binding Amendment

### ISSUE THREAD

**Issue by Mythacri** [Mythacri/Mythacri-Foundry-Scripts#94]
- [x] Add method to craft a spiritbinding. This creates a new consumable type ('Bound Spirit'?). These should not stack.
- [x] Add 'grade' property to essences.
- [x] Use grade property when several properties of the created techniques..
- [x] Store the grade of the created item internally on the created item.
- [x] Store the uuid of the recipe used in the crafting internally on the created item.
- [x] Create method to transfer the technique of the created item onto the owner of the item (not a target).

# Original post
The spirit binding crafting system involves a scaling value that needs to be accounted for known as the "Spirit Grade".

Grades have 6 stages that go from 1-6 (Although some upon suggestion these can be renamed before being fully implemented if there's a better idea). 

The spirit binding techniques are being put in as spells on items using the items with spells module. The techniques need to be able to reference the spirit grade of an item so that they can be scaled properly. I'm not certain what the best way to implement this would be.

**Comment by krbz999** [comment]
Some thoughts:

If each essence has both an identifier and a grade, they should no longer stack - at least they should not stack on the actor sheet depending solely on the identifier as is the current case.

I don't believe these need to be added using the 'Items With Spells' module, which will hopefully soon be deprecated (I plan on incorporating it fully in the system). The spells themselves can be added fully as standalone granted items to the actor. We can possibly implement some functionality to make the spells be 'destroyed' when they can no longer be used.

The benefit of having the crafting recipe for spiritbinding grant the spell, and not an item that has spells, is that the saving throw DC (if any) can be set at that point in time to a flat value depending on the essence used in the crafting process.

Is there a benefit to having the spells be embedded on equippable items with the 'Items With Spells' module?

**Comment by Mythacri** [comment]
The reason for the spell being used with the items with spells module was that the spirit is narratively bound to a wooden or stone object. That way someone else can take the object and use it as well; allowing the items to be traded amongst players or with NPC's logically.

However we could do something similar to how the rune carving is set to work where the effect can be transferred to another item? If the item being crafted as a spell works best though then I will plan on having it work like that and then the player could have the option to drag and drop the spell on to an item of their choosing. Would that be possible?

**Comment by krbz999** [comment]
Is there a particular reason they should be spells at all? The created option could be a new consumable type, which would also solve the ability to have the item be destroyed after a number of uses.

**Comment by Mythacri** [comment]
I was not planning on having these disappear after a set amount of uses. The only reason I had them as spells was because I believe when we talked about them initially that was the recommended way to handle them. If making them just as an item would be better then I'm all for that. I believe the reasoning for spells was that they were "actions" that could be put onto other items.

**Comment by krbz999** [comment]
Can one item have only one spell or multiple?

**Comment by Mythacri** [comment]
As it is now an item can have multiple but if any of these parts of the crafting system are out of the range of reason I'm not opposed to overhauling it.

**Comment by Mythacri** [comment]
Yes, that is the plan. One craft, one action. Putting it on an equipment will work then for sure. If scaling is an issue I can go with the other option which is more specific but can be handled narratively. "This item needs an undead essence, from a wraith" etc which would then be it's own recipe and item.

**Comment by Mythacri** [comment]
Okay, FINAL decision (hopefully)

Spiritbinding binds spirit techniques to an item where they are held. 
These items can then be used to grant the spirit technique held onto it to an actor.
An item can only hold one spirit at a time.
The grade of the spirit affects how strong the technique is with most techniques scaling up based on the grade.
A creature cannot have multiple of the same technique. A creature can replace a technique with a stronger version of it if they acquire it.

**Comment by krbz999** [comment]
Some final questions.

> The grade of the spirit affects how strong the technique is with most techniques scaling up based on the grade.

When is the grade of the essence determined?

> A creature can replace a technique with a stronger version of it if they acquire it.

How limited is the set of techniques?

**Comment by Mythacri** [comment]
The grade of the essence is determined when the creature is defeated and looted.

The set of techniques works like the other crafting systems where there are base "recipes" that everyone knows and new ones can be learned later. If we were to cap the amount of techniques an individual could know in full I would say the cap should be double their proficiency bonus but lets not enforce that just yet.

**Comment by krbz999** [comment]
Is a 'stronger version' of a technique taken to mean the same "recipe" but using essence of a higher grade?

**Comment by Mythacri** [comment]
Yes, the same recipe but using a higher grade. If this is possible. If not, then I will just make multiple recipes.

**Comment by krbz999** [comment]
Using the same recipe would be ideal; the uuid of the recipe item could then be used to determine whether two created techniques are 'the same' (and one possibly stronger than the other).
