### ISSUE TITLE
Marbles Currency

### ISSUE THREAD

**Issue by Mythacri** [Mythacri/Mythacri-Foundry-Scripts#95]
As discussed our currency system needs to be updated to use 'marbles' instead of gold pieces. 

For the system money is simply being calculated with one currency that other objects will revolve around in the form of small golden marbles. The other currencies need to be removed and it needs to be renamed.

**Comment by krbz999** [comment]
What is the weight of one marble and do we track currency weight?

**Comment by Mythacri** [comment]
Each marble should weigh 0.01 lbs. For inventory purposes I wouldn't count it against carry weight. An exorbitant amount of marbles, like over 3000, should maybe be capped?  Not that players can't earn more but at that point it's like, get a chest or make multiple trips or something I don't know. For now, marbles are 0.01 lbs and are the only currency.
